from __future__ import annotations
from typing import Any
from datetime import datetime
from pywise.utils.naming import to_camel_case
from pywise.models.base.connectwise_model import ConnectWiseModel
from pywise.models.manage.MemberDeactivationSalesActivityModel import MemberDeactivationSalesActivityModel
from pywise.models.manage.MemberDeactivationServiceTeamModel import MemberDeactivationServiceTeamModel
from pywise.models.manage.MemberDeactivationCompanyTeamModel import MemberDeactivationCompanyTeamModel
from pywise.models.manage.MemberDeactivationWorkflowModel import MemberDeactivationWorkflowModel
from pywise.models.manage.MemberDeactivationStatusWorkflowModel import MemberDeactivationStatusWorkflowModel
from pywise.models.manage.MemberDeactivationServiceTemplateModel import MemberDeactivationServiceTemplateModel
from pywise.models.manage.MemberDeactivationOpportunityModel import MemberDeactivationOpportunityModel
from pywise.models.manage.MemberDeactivationSalesTeamModel import MemberDeactivationSalesTeamModel
from pywise.models.manage.MemberDeactivationProjectManagerModel import MemberDeactivationProjectManagerModel
from pywise.models.manage.MemberDeactivationProjectManagerModel import MemberDeactivationProjectManagerModel
from pywise.models.manage.MemberDeactivationProjectManagerModel import MemberDeactivationProjectManagerModel
from pywise.models.manage.MemberDeactivationKnowledgebaseArticleModel import MemberDeactivationKnowledgebaseArticleModel
from pywise.models.manage.MemberDeactivationMyCompanyPresidentRoleModel import MemberDeactivationMyCompanyPresidentRoleModel
from pywise.models.manage.MemberDeactivationMyCompanyCOORoleModel import MemberDeactivationMyCompanyCOORoleModel
from pywise.models.manage.MemberDeactivationMyCompanyControllerRoleModel import MemberDeactivationMyCompanyControllerRoleModel
from pywise.models.manage.MemberDeactivationMyCompanyDispatchRoleModel import MemberDeactivationMyCompanyDispatchRoleModel
from pywise.models.manage.MemberDeactivationMyCompanyServiceManagerRoleModel import MemberDeactivationMyCompanyServiceManagerRoleModel
from pywise.models.manage.MemberDeactivationMyCompanyDutyManagerRoleModel import MemberDeactivationMyCompanyDutyManagerRoleModel
from pywise.models.manage.MemberDeactivationDepartmentMananagerModel import MemberDeactivationDepartmentMananagerModel
from pywise.models.manage.MemberDeactivationDispatchMemberModel import MemberDeactivationDispatchMemberModel
from pywise.models.manage.MemberDeactivationServiceMangerModel import MemberDeactivationServiceMangerModel
from pywise.models.manage.MemberDeactivationDutyManagerModel import MemberDeactivationDutyManagerModel
from pywise.models.manage.MemberDeactivationSendFromEmailNotifyModel import MemberDeactivationSendFromEmailNotifyModel

class MemberDeactivationModel(ConnectWiseModel):
    activity: MemberDeactivationSalesActivityModel
    service_team: MemberDeactivationServiceTeamModel
    company_team: list[MemberDeactivationCompanyTeamModel]
    workflow_email: MemberDeactivationWorkflowModel
    service_status_workflow: list[MemberDeactivationStatusWorkflowModel]
    ticket_template: MemberDeactivationServiceTemplateModel
    opportunity: MemberDeactivationOpportunityModel
    sales_team: MemberDeactivationSalesTeamModel
    project_manager: MemberDeactivationProjectManagerModel
    project_time_approver: MemberDeactivationProjectManagerModel
    project_expense_approver: MemberDeactivationProjectManagerModel
    knowledge_base_article: MemberDeactivationKnowledgebaseArticleModel
    my_company_president: MemberDeactivationMyCompanyPresidentRoleModel
    my_company_c_o_o: MemberDeactivationMyCompanyCOORoleModel
    my_company_controller: MemberDeactivationMyCompanyControllerRoleModel
    my_company_dispatch: MemberDeactivationMyCompanyDispatchRoleModel
    my_company_service_manager: MemberDeactivationMyCompanyServiceManagerRoleModel
    my_company_duty_manager_role: MemberDeactivationMyCompanyDutyManagerRoleModel
    department_manager: MemberDeactivationDepartmentMananagerModel
    dispatch_member: MemberDeactivationDispatchMemberModel
    service_manager: MemberDeactivationServiceMangerModel
    duty_manager: MemberDeactivationDutyManagerModel
    send_from_email_notify: MemberDeactivationSendFromEmailNotifyModel
    delete_open_time_sheets_flag: bool

    class Config:
        alias_generator = to_camel_case
        allow_population_by_field_name = True
        use_enum_values = True